CREATE TABLE Oddelenie (
  ident INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 nazov VARCHAR(30)CHECK(>5) NOT NULL,
 kod VARCHAR(4)CHECK(>1) NOT NULL,
 uroven REAL
);

CREATE TABLE Zamestnanec (
  ident INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 ident_Oddelenie INTEGER,
 meno VARCHAR(30)CHECK(>2) NOT NULL,
 priezvisko VARCHAR(30)CHECK(>2) NOT NULL,
 vek INTEGER
);

ALTER TABLE Zamestnanec ADD CONSTRAINT Oddelenie_fkey FOREIGN KEY (ident_Oddelenie) REFERENCES Oddelenie(ident)